//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _RestoranWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public Adres()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int AdresId { get; set; }
        public string Sehir { get; set; }
        public string Id { get; set; }
        public int SemtId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Semt Semt { get; set; }
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
