//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _RestoranWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoran
    {
        public Restoran()
        {
            this.Siparis = new HashSet<Siparis>();
            this.Semt = new HashSet<Semt>();
            this.Urun = new HashSet<Urun>();
        }
    
        public int RestoranId { get; set; }
        public string RestoranAdi { get; set; }
        public bool Durum { get; set; }
        public string OrtSipSure { get; set; }
        public decimal RezervasyonUcreti { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        public virtual ICollection<Siparis> Siparis { get; set; }
        public virtual ICollection<Semt> Semt { get; set; }
        public virtual ICollection<Urun> Urun { get; set; }
    }
}
