//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _RestoranWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semt
    {
        public Semt()
        {
            this.Adres = new HashSet<Adres>();
            this.Restoran = new HashSet<Restoran>();
        }
    
        public int SemtId { get; set; }
        public string SemtAdi { get; set; }
    
        public virtual ICollection<Adres> Adres { get; set; }
        public virtual ICollection<Restoran> Restoran { get; set; }
    }
}
