//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _RestoranWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public Siparis()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int SiparisId { get; set; }
        public System.DateTime SiparisTarih { get; set; }
        public Nullable<int> AdresId { get; set; }
        public string Id { get; set; }
        public int RestoranId { get; set; }
        public int UrunId { get; set; }
        public Nullable<int> UrunMiktari { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Restoran Restoran { get; set; }
        public virtual Urun Urun { get; set; }
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
