//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _RestoranWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public Urun()
        {
            this.Siparis = new HashSet<Siparis>();
            this.Restoran = new HashSet<Restoran>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunResim { get; set; }
        public Nullable<decimal> UrunFiyati { get; set; }
    
        public virtual ICollection<Siparis> Siparis { get; set; }
        public virtual ICollection<Restoran> Restoran { get; set; }
    }
}
